name: CI Pipeline

on:
  push:
    branches:
      - main  # Branch name if necessary
  pull_request:
    branches:
      - main  # Branch name if necessary

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dotnet-version: ['8.0.x']

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
          
      - name: List directory contents
        run: ls -R ./bin/Debug/net8.0
        
      - name: Set file permissions
        run: chmod +x ./bin/Debug/net8.0/playwright.ps1

      - name: Check PowerShell version
        run: pwsh --version





      - name: Install Playwright Browsers
        run: pwsh ./bin/Debug/net8.0/playwright.ps1 install
        shell: pwsh
      
      - name: Restore dependencies
        run: dotnet restore

      - name: Build the solution
        run: dotnet build --configuration Release --no-restore

      - name: Run tests
        run: dotnet test --no-restore --verbosity normal
