name: CI Pipeline

on:
  push:
    branches:
      - main  # Branch name if necessary
  pull_request:
    branches:
      - main  # Branch name if necessary

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dotnet-version: ['8.0.x']

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
          
      - name: Checkout code
        uses: actions/checkout@v3
    
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Install Playwright Browsers
        run: xvfb-run pwsh ./bin/Debug/net8.0/playwright.ps1 install
        shell: pwsh
          
      - name: Build the project
        run: dotnet build
    
      - name: List files in the build output directory
        run: ls -R ./bin/Debug/net8.0
    
      - name: Install Playwright Browsers
        run: pwsh ./bin/Debug/net8.0/playwright.ps1 install
        shell: pwsh

      
      - name: Restore dependencies
        run: dotnet restore

      - name: Build the solution
        run: dotnet build --configuration Release --no-restore

      - name: Run tests
        run: dotnet test --no-restore --verbosity normal
